---
- hosts: localhost
  tasks:
    - name: install RPMFusion repos for wifi
      dnf:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'https://download0.rpmfusion.org/free/fedora/rpmfusion-free-release-25.noarch.rpm'
        - 'https://download0.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-25.noarch.rpm'
    - name: install packages we need
      dnf:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'akmods'
        - 'kernel-devel'
        - 'broadcom-wl'
        - 'lm_sensors'
        - 'gcc-c++'
        - 'NetworkManager-openconnect-gnome'
    - name: run akmods
      command: akmods

    - name: clone mbpfan repo
      git:
        repo: https://github.com/dgraziotin/mbpfan
        dest: /opt/mbpfan
        clone: yes
        update: no
    - name: run make for mbpfan
      command: make
      args:
        chdir: /opt/mbpfan
    - name: run make install for mbpfan
      command: make install
      args:
        chdir: /opt/mbpfan
    - name: run make tests for mbpfan
      command: make tests
      args:
        chdir: /opt/mbpfan
    - name: copy unit file for mbpfan
      command: cp /opt/mbpfan/mbpfan.service /etc/systemd/system
      args:
        creates: /etc/systemd/system/mbpfan.service
    - name: start and enable mbpfan.service
      systemd:
        name: mbpfan.service
        state: started
        enabled: True

    - name: clone gpu-switch repo
      git:
        repo: https://github.com/0xbb/gpu-switch
        dest: /opt/gpu-switch
        clone: yes
        update: no
